package com.hp.j2sh.project.entity;
// Generated 14 Jul, 2015 11:33:44 PM by Hibernate Tools 4.3.1



/**
 * AllCommunities generated by hbm2java
 */
public class AllCommunities  implements java.io.Serializable {


     private Integer communityId;
     private String communityName;
     private AllUsers allUsers;

    public AllCommunities() {
    }

    public AllCommunities(String communityName, Integer communityId) {
       this.communityName = communityName;
       this.communityId = communityId;
    }
   
    public Integer getCommunityId() {
        return this.communityId;
    }
    
    public void setCommunityId(Integer communityId) {
        this.communityId = communityId;
    }
    public String getCommunityName() {
        return this.communityName;
    }
    
    public void setCommunityName(String communityName) {
        this.communityName = communityName;
    }
    public AllUsers getAllUsers() {
        return this.allUsers;
    }
    
    public void setAllUsers(AllUsers allUsers) {
        this.allUsers = allUsers;
    }




}


