package com.hp.j2sh.project.entity;
// Generated 14 Jul, 2015 11:33:44 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * AllUsers generated by hbm2java
 */
public class AllUsers  implements java.io.Serializable {


     private Integer userId;
     private String username;
     private String password;
     private UserEducationalDetails userEducationalDetails;
     private UserOtherDetails userOtherDetails;
     private UserPersonalDetails userPersonalDetails;
     private UserWorkDetails userWorkDetails;
     private Set allCommunities = new HashSet(0);

    public AllUsers() {
    }

	
    public AllUsers(String username, String password) {
        this.username = username;
        this.password = password;
    }
    public AllUsers(String username, String password, UserEducationalDetails userEducationalDetails, UserOtherDetails userOtherDetails, UserPersonalDetails userPersonalDetails, UserWorkDetails userWorkDetails, Set allCommunities) {
       this.username = username;
       this.password = password;
       this.userEducationalDetails = userEducationalDetails;
       this.userOtherDetails = userOtherDetails;
       this.userPersonalDetails = userPersonalDetails;
       this.userWorkDetails = userWorkDetails;
       this.allCommunities = allCommunities;
    }
   
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public UserEducationalDetails getUserEducationalDetails() {
        return this.userEducationalDetails;
    }
    
    public void setUserEducationalDetails(UserEducationalDetails userEducationalDetails) {
        this.userEducationalDetails = userEducationalDetails;
    }
    public UserOtherDetails getUserOtherDetails() {
        return this.userOtherDetails;
    }
    
    public void setUserOtherDetails(UserOtherDetails userOtherDetails) {
        this.userOtherDetails = userOtherDetails;
    }
    public UserPersonalDetails getUserPersonalDetails() {
        return this.userPersonalDetails;
    }
    
    public void setUserPersonalDetails(UserPersonalDetails userPersonalDetails) {
        this.userPersonalDetails = userPersonalDetails;
    }
    public UserWorkDetails getUserWorkDetails() {
        return this.userWorkDetails;
    }
    
    public void setUserWorkDetails(UserWorkDetails userWorkDetails) {
        this.userWorkDetails = userWorkDetails;
    }
    public Set getAllCommunities() {
        return this.allCommunities;
    }
    
    public void setAllCommunities(Set allCommunities) {
        this.allCommunities = allCommunities;
    }




}


