package com.hp.j2sh.project.entity;
// Generated 14 Jul, 2015 11:33:44 PM by Hibernate Tools 4.3.1



/**
 * CommunityUsers generated by hbm2java
 */
public class CommunityUsers  implements java.io.Serializable {


     private Integer count;
     private int communityId;
     private int userId;

    public CommunityUsers() {
    }

    public CommunityUsers(int communityId, int userId) {
       this.communityId = communityId;
       this.userId = userId;
    }
   
    public Integer getCount() {
        return this.count;
    }
    
    public void setCount(Integer count) {
        this.count = count;
    }
    public int getCommunityId() {
        return this.communityId;
    }
    
    public void setCommunityId(int communityId) {
        this.communityId = communityId;
    }
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }




}


