package com.hp.j2sh.project.entity;
// Generated 14 Jul, 2015 11:33:44 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * UserPersonalDetails generated by hbm2java
 */
public class UserPersonalDetails  implements java.io.Serializable {


     private Integer userId;
     private String firstName;
     private String middleName;
     private String lastName;
     private String emailPrimary;
     private String emailSecondary;
     private long contactPrimary;
     private Long contactSecondary;
     private Date dob;
     private String gender;
     private AllUsers allUsers;

    public UserPersonalDetails() {
    }

	
    public UserPersonalDetails(String firstName, String emailPrimary, long contactPrimary) {
        this.firstName = firstName;
        this.emailPrimary = emailPrimary;
        this.contactPrimary = contactPrimary;
    }
    public UserPersonalDetails(String firstName, String middleName, String lastName, String emailPrimary, String emailSecondary, long contactPrimary, Long contactSecondary, Date dob, String gender) {
       this.firstName = firstName;
       this.middleName = middleName;
       this.lastName = lastName;
       this.emailPrimary = emailPrimary;
       this.emailSecondary = emailSecondary;
       this.contactPrimary = contactPrimary;
       this.contactSecondary = contactSecondary;
       this.dob = dob;
       this.gender = gender;
    }
   
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getMiddleName() {
        return this.middleName;
    }
    
    public void setMiddleName(String middleName) {
        this.middleName = middleName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getEmailPrimary() {
        return this.emailPrimary;
    }
    
    public void setEmailPrimary(String emailPrimary) {
        this.emailPrimary = emailPrimary;
    }
    public String getEmailSecondary() {
        return this.emailSecondary;
    }
    
    public void setEmailSecondary(String emailSecondary) {
        this.emailSecondary = emailSecondary;
    }
    public long getContactPrimary() {
        return this.contactPrimary;
    }
    
    public void setContactPrimary(long contactPrimary) {
        this.contactPrimary = contactPrimary;
    }
    public Long getContactSecondary() {
        return this.contactSecondary;
    }
    
    public void setContactSecondary(Long contactSecondary) {
        this.contactSecondary = contactSecondary;
    }
    public Date getDob() {
        return this.dob;
    }
    
    public void setDob(Date dob) {
        this.dob = dob;
    }
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    public AllUsers getAllUsers() {
        return this.allUsers;
    }
    
    public void setAllUsers(AllUsers allUsers) {
        this.allUsers = allUsers;
    }




}


