package com.hp.j2sh.project.entity;
// Generated 14 Jul, 2015 11:33:44 PM by Hibernate Tools 4.3.1



/**
 * UserWorkDetails generated by hbm2java
 */
public class UserWorkDetails  implements java.io.Serializable {


     private Integer userId;
     private String organization;
     private String position;
     private Integer workSince;
     private AllUsers allUsers;

    public UserWorkDetails() {
    }

    public UserWorkDetails(String organization, String position, Integer workSince) {
       this.organization = organization;
       this.position = position;
       this.workSince = workSince;
    }
   
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
    public String getOrganization() {
        return this.organization;
    }
    
    public void setOrganization(String organization) {
        this.organization = organization;
    }
    public String getPosition() {
        return this.position;
    }
    
    public void setPosition(String position) {
        this.position = position;
    }
    public Integer getWorkSince() {
        return this.workSince;
    }
    
    public void setWorkSince(Integer workSince) {
        this.workSince = workSince;
    }
    public AllUsers getAllUsers() {
        return this.allUsers;
    }
    
    public void setAllUsers(AllUsers allUsers) {
        this.allUsers = allUsers;
    }




}


