package com.hp.j2sh.project.other;
// Generated 14 Jul, 2015 11:33:44 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Post generated by hbm2java
 */
public class Post  implements java.io.Serializable {


     private Integer count;
     private String content;
     private int userId;
     private int communityId;
     private Date dateTime;

    public Post(String content, int userId, int communityId, Date dateTime) {
        this.content = content;
        this.userId = userId;
        this.communityId = communityId;
        this.dateTime = dateTime;
    }
    
    public Post() {
        
    }

    public int getCommunityId() {
        return communityId;
    }

    public void setCommunityId(int communityId) {
        this.communityId = communityId;
    }
   
    public Integer getCount() {
        return this.count;
    }
    
    public void setCount(Integer count) {
        this.count = count;
    }
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }
    public Date getDateTime() {
        return this.dateTime;
    }
    
    public void setDateTime(Date dateTime) {
        this.dateTime = dateTime;
    }




}


